website/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.AboutAuthorView.as_view(), name='author'),
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
]

website/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='posts_home_page'),
    path('projects/', views.creativity, name='creativity'),
    path('projects/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('projects/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'
handler403 = 'core.views.forbidden'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

website/projects/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel

User = get_user_model()

NUM_CHARACTERS: int = 15


class Category(CreatedModel):
    name = models.CharField(
        max_length=256,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
    )

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ['slug', ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Post(CreatedModel):
    title = models.CharField(max_length=255)
    text = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE,
        null=True,
        related_name='posts'
    )
    description = models.TextField(null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='projects'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='projects/',
        blank=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:NUM_CHARACTERS]

website/projects/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        labels = {'text': 'Текст записи'}
        help_texts = {
            'text': 'Текст нового поста',
        }
        required = {'text': True}
        fields = ['text', 'image']

website/projects/views.py
import django.db.models.query
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .forms import PostForm
from .models import Post, User

NUM_OUTPUT: int = 10
NUM_CHARACTERS: int = 30


def index(request):
    return render(request, 'about/author.html')


@cache_page(20, key_prefix='creativity_page')
def creativity(request):
    post_list = Post.objects.all()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number)
    context = {
        'page_obj': page_obj,
        'view_name': creativity.__name__
    }
    return render(request, 'projects/index.html', context)


def post_detail(request, post_id):
    certain_post = get_object_or_404(Post, pk=post_id)
    posts_number = Post.objects.select_related('author').filter(
        author=certain_post.author
    ).count()
    context = {
        'posts_number': posts_number,
        'post': certain_post,
        'title': certain_post.text[:NUM_CHARACTERS],
    }
    return render(request, 'projects/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            author = User.objects.get(pk=request.user.id)
            post = Post(
                text=form.cleaned_data['text'],
                author=author,
            )
            post.save()
            return redirect('projects:profile', author.username)
    form = PostForm()
    context = {
        'form': form,
        'is_edit': False
    }
    return render(request, 'projects/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.user.id is not post.author.id:
        return redirect('projects:post_detail', post_id)
    else:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post)
        if request.method == 'POST':
            if form.is_valid():
                post.text = form.cleaned_data['text']
                post.save()
                form.save()
                return redirect('projects:post_detail', post_id)
        else:
            context = {
                'form': form,
                'is_edit': True,
                'post_id': post_id
            }
            return render(request, 'projects/create_post.html', context)


def get_page_obj(
        object_list: django.db.models.query.QuerySet,
        page_number: None
) -> django.core.paginator.Page:
    paginator = Paginator(object_list, NUM_OUTPUT)
    return paginator.get_page(page_number)

website/templates/projects/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать запись
          {% else %}
          Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% include 'includes/form_error_processing.html' %}
          <form method="post"
                enctype="multipart/form-data"
                action="
                {% if is_edit %}
                  {% url 'projects:post_edit' post_id=post_id %}
                {% else %}
                  {% url 'projects:post_create' %}
                {% endif %}
                "
          >
          {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
              <small
                id="{{ field.id_for_label }}-help"
                class="form-text text-muted"
              >
              {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/projects/index.html
{% extends 'base.html' %}
{% block title %}
  My projects
{% endblock %}
{% block content %}
  {% load cache %}
  {% cache 20 index_page %}
  <div class="container py-5">
    <article>
      <h3>My projects</h3>
      {% for post in page_obj %}
        {% include 'includes/body_of_post.html' %}
        <p>
          <a href="{% url 'projects:post_detail' post.id %}">Read</a>
        </p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
  {% endcache %}
{% endblock %}

website/templates/projects/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ title }}
{% endblock %}
{% block content %}
  {% include 'includes/body_of_post_detail.html' %}
{% endblock %}