website/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.AboutAuthorView.as_view(), name='author'),
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
]

website/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='posts_home_page'),
    path('projects/', views.creativity, name='creativity'),
    path('projects/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('projects/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'
handler403 = 'core.views.forbidden'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

website/templates/includes/body_of_post.html
{% load thumbnail %}
<ul>
  <li>
    Category: {{ post.category.name }}
  </li>
  <li>
    Name: {{ post.title }}
  </li>
</ul>

website/templates/includes/body_of_post_detail.html
{% load thumbnail %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        The number of posts:  <span >{{ posts_number }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Author:  <span >Alexey Akimov</span>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
  </article>
</div>

website/templates/includes/footer.html
 <p>© {{ year }} Alexey Akimov. All Rights Reserved</p>

website/templates/includes/form_error_processing.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

website/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-dark" style="background-color: MidnightBlue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'projects:posts_home_page' %}">
      <span style="color:white">Nothing is impossible</span>
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' or view_name  == 'projects:posts_home_page' %}active{% endif %}"
           href="{% url 'about:author' %}">About
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'projects:creativity' %}active{% endif %}"
           href="{% url 'projects:creativity' %}">Creativity
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:contacts' %}active{% endif %}"
           href="{% url 'about:contacts' %}">Contacts
        </a>
      </li>
    </ul>
    {% endwith %}
  </div>
</nav>

website/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

website/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if view_name  == 'index' %}active{% endif %}"
          href="{% url 'projects:posts_home_page' %}"
        >
          Все авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}